openapi: 3.1.0
info:
  title: Facade Agent for MCP - MVP API
  version: 1.3.0
  description: publish MCPs and search via RAG; search returns full MCP details.

servers:
  - url: https://example.com

paths:
  /publish:
    post:
      operationId: publish
      summary: Register an MCP server (no auth, no validation)
      description: Vectorizes metaDescription to vector DB and stores full record in Supabase.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/PublishRequest" }
            examples:
              sample:
                value:
                  iconUrl: "https://example.com/icon.png"
                  title: "PDF Summarizer"
                  metaDescription: "Summarize PDF documents"
                  fullDescription: "Extract text from PDFs and generate concise summaries using an LLM."
                  endpoint: "https://api.example.com/pdf"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/PublishResponse" }
              examples:
                sample: { value: { id: "mcp_001", status: "ok" } }

  /search:
    post:
      operationId: search
      summary: Search MCPs using LLM + RAG (Top 3 + natural language answer)
      description: Embed the query, retrieve Top 3 from vector DB, fetch full metadata, generate an explanation.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/SearchRequest" }
            examples:
              sample: { value: { message: "I want to summarize a PDF" } }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: { $ref: "#/components/schemas/SearchResponse" }
              examples:
                sample:
                  value:
                    queryEcho: "I want to summarize a PDF"
                    candidates:
                      - id: "mcp_001"
                        title: "PDF Summarizer"
                        iconUrl: "https://example.com/icon.png"
                        endpoint: "https://api.example.com/pdf"
                        metaDescription: "Summarize PDF documents"
                        fullDescription: "Extracts text from PDFs and summarizes it using an LLM."
                      - id: "mcp_002"
                        title: "Web Crawler"
                        iconUrl: "https://example.com/crawler.png"
                        endpoint: "https://api.example.com/crawl"
                        metaDescription: "Fetch and extract web page text"
                        fullDescription: "Crawls a given URL and extracts visible text for downstream tasks."
                      - id: "mcp_003"
                        title: "Translator"
                        iconUrl: "https://example.com/translator.png"
                        endpoint: "https://api.example.com/translate"
                        metaDescription: "Translate text between languages"
                        fullDescription: "Performs multilingual text translation for processed content."
                    llmAnswer: |
                      Goal: summarize a PDF. First, use Web Crawler to extract the text,
                      then send the text to PDF Summarizer. If needed, translate results
                      with Translator.

  /health:
    get:
      operationId: health
      summary: Health check
      responses:
        "200": { description: OK }

components:
  schemas:
    PublishRequest:
      type: object
      required: [iconUrl, title, metaDescription, fullDescription, endpoint]
      properties:
        iconUrl: { type: string, format: uri }
        title: { type: string }
        metaDescription: { type: string }
        fullDescription: { type: string }
        endpoint: { type: string, format: uri }

    PublishResponse:
      type: object
      properties:
        id: { type: string }
        status: { type: string, enum: [ok] }

    SearchRequest:
      type: object
      required: [message]
      properties:
        message: { type: string, description: "User natural-language query" }

    SearchResponse:
      type: object
      required: [queryEcho, candidates, llmAnswer]
      properties:
        queryEcho: { type: string }
        candidates:
          type: array
          items: { $ref: "#/components/schemas/McpSummary" }
        llmAnswer: { type: string }

    McpSummary:
      type: object
      required: [id, title, endpoint, metaDescription, fullDescription]
      properties:
        id: { type: string }
        title: { type: string }
        iconUrl: { type: string, format: uri }
        endpoint: { type: string, format: uri }
        metaDescription: { type: string }
        fullDescription: { type: string }
