import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "@/components/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className="flex flex-col min-h-screen">
          <Navigation />
          <main className="flex-1 container max-w-7xl mx-auto px-5 py-5">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
